pullboy:
    workdir: '~/pullboy'
    script:
        - git pull origin master
        - make deploy
    token: 'thisisnosecret'
    active: true
asecrettokenforgitlab:
    environment:
        - DB_USER_NAME: '1'
        - DB_PWD: '2'
    workdir: '~/pullboy'
    script:
        - echo 'run my fancy web server'
    active: true
    branch: master
    gitlab: true
