pullboy:
    workdir: '~/pullboy'
    script:
        - git pull origin master
        - make deploy
    token: 'thisisnosecret'
    active: true
asecrettokenforgitlab:
    environment:
        - SOME_ENV_FLAG: '1'
        - SOME_ENV_FLAG2: '2'
    workdir: '~/pullboy'
    script:
        - echo 'hi'
    active: true
    branch: master
    gitlab: true
