pullboy:
    workdir: '~/pullboy'
    script:
        - git pull origin master
        - make deploy
    token: 'thisisnosecret'
    active: true
asecrettokenforgitlab:
    workdir: '~/pullboy'
    script:
        - echo 'hi'
    active: true
    branch: master
    gitlab: true
